WIP Uploading and attaching an image to a post
s12m/tbf-instagram-phoenix pull request #12
Opened 2019-11-19 23:31 UTC by NaitoYuki

https://www.phoenixframework.org/blog/file-uploads

2019-11-19 23:32 UTC, NaitoYuki commented
@mokichi こちらまだですが、なんかうまくファイルが保存されない・・・

2019-11-19 23:32 UTC, NaitoYuki commented
https://www.phoenixframework.org/blog/file-uploads

2019-11-20 01:22 UTC, mokichi commented
@NaitoYuki `Plug.Upload` はファイルをサーバに送るところまでしか面倒を見てくれないので、ファイルの保存やDBへのURLの保存は自前で実装する必要があります。↓が参考になるかなと

https://codeday.me/jp/qa/20190621/1061165.html

2019-11-20 01:26 UTC, NaitoYuki commented
あ〜やっぱそうなんですね。探し見ても大抵arcを使ってる感じでした・・・

2019-11-20 01:27 UTC, mokichi commented
現実的にはライブラリはまず使うだろうし、環境によって保存先をS3やCloudinaryに変えるとかも `arc` は対応してるので、使っちゃってもいいかもしれませんね

2019-11-24 07:39 UTC, NaitoYuki commented
実装が簡単な方がいい気がするので、Arcを使用しました。

2019-11-29 14:14 UTC, mokichi requested changes

2019-11-29 14:14 UTC, mokichi commented on lib/instagram_web/uploaders/image_uploader.ex
> +    Application.get_env(:phoenix, :upload_dir)
違う `Post` で同じファイル名の画像をアップすると、ファイルが上書きされてしまいますね

2019-11-29 14:14 UTC, mokichi commented on lib/instagram_web/uploaders/image_uploader.ex
> +defmodule Instagram.ImageUploader do
細かいところですが、このモジュール名なら `/lib/instagram/uploaders/` に置いたほうがいいような

2019-12-01 02:29 UTC, NaitoYuki commented on lib/instagram_web/uploaders/image_uploader.ex
> +defmodule Instagram.ImageUploader do
以下のコマンドで生成したらできた感じです。こっちが標準的なのか？
```
❯ docker-compose run --rm web mix arc.g image_uploader
```

2019-12-01 03:30 UTC, NaitoYuki commented on lib/instagram_web/uploaders/image_uploader.ex
> +    Application.get_env(:phoenix, :upload_dir)
これでいけるとおもったが、scope.idのフォルダが作られないな。なぜだ。
```
  def storage_dir(version, {file, scope}) do
    "uploads/images/posts/#{scope.id}"
  end
```

2019-12-01 08:37 UTC, mokichi commented on lib/instagram_web/uploaders/image_uploader.ex
> +defmodule Instagram.ImageUploader do
`arg.g` はディレクトリ構成がPhoenix1.2系までのもの前提になってて古いんですよね。。まあRaisと違ってモジュール名とディレクトリ構成は関係ないので、このままでも大丈夫です

2019-12-01 08:59 UTC, mokichi commented on lib/instagram_web/uploaders/image_uploader.ex
> +    Application.get_env(:phoenix, :upload_dir)
`arc_ecto` を使うと、 `Post` 生成と同時にファイル保存する際にまだ `Post` が生成されてないので `scope.id == nil` になっちゃうっていうのが、GlobalTreehouseでもあったような。

`Posts.create_post/1` で `Post` 生成 → ファイル保存と分けて処理すれば解決しそうです。GlobalTreehouseではレコード生成前にディレクトリ名を生成して、そこに保存されるように設定してますね

2019-12-02 08:40 UTC, NaitoYuki commented on lib/instagram_web/uploaders/image_uploader.ex
> +defmodule Instagram.ImageUploader do
個人的にはuploadersの方がrailsのcarriawaveに近くていいかなって気がします。

2019-12-04 14:16 UTC, NaitoYuki commented
できました。ect.resetが必要

あと、この警告消えない。
```
web_1   |   lib/instagram_web/uploaders/image_uploader.ex:5: Instagram.ImageUploader.Type (module)
web_1   |
web_1   | warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module Instagram.ImageUploader.Type)
web_1   |   lib/instagram_web/uploaders/image_uploader.ex:5: Instagram.ImageUploader.Type (module)
```

2019-12-05 04:25 UTC, mokichi commented
@NaitoYuki プッシュ忘れ？

2019-12-05 10:50 UTC, mokichi approved these changes
@NaitoYuki LGTM! 他の人はどうやってるんでしょうね・・

2019-12-05 10:50 UTC, merged